backend:
  replicas: 2
  image:
    repository: antoni0832/backend-app
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      memory: 250Mi
      cpu: 200m
    limits:
      memory: 400Mi
      cpu: 500m
  service:
    type: ClusterIP
    ports:
      name: flask
      port: 5000
      targetPort: 5000
      protocol: TCP

frontend:
  replicas: 1
  image:
    repository: antoni0832/frontend-app
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  service:
    type: ClusterIP
    ports:
      name: http
      port: 80
      targetPort: 8080
      protocol: TCP

mysql:
  replicas: 1
  image:
    repository: mysql
    tag: 8.4.6
    pullPolicy: Always
  service:
    type: ClusterIP
    ports:
      name: mysql-db
      port: 3306
      targetPort: 3306
      protocol: TCP
  volumeMounts:
  - name: mysql-db
    mountPath: /var/lib/mysql
  volumes:
    name: mysql-db
  pvc:
    storageClassName: "standard"
    storage: 4Gi

redis:
  replicas: 1
  image:
    repository: redis
    tag: 8.2.2-alpine
    pullPolicy: Always
  service:
    type: ClusterIP
    ports:
      name: redis-db
      port: 6379
      targetPort: 6379
      protocol: TCP
  volumeMounts:
  - name: redis-db
    mountPath: /data
  volumes:
    name: redis-db
  pvc:
    storageClassName: "standard"
    storage: 2Gi
