apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{ include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.ports.port }}
    targetPort: {{ .Values.frontend.service.ports.targetPort }}
    protocol: {{ .Values.frontend.service.ports.protocol }}
    name: {{ .Values.frontend.service.ports.name}} 
  selector:
    app: {{ .Release.Name }}-frontend
