name: master

on:
  push:
    branches: 
    - main

jobs:
  lint-backend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout backend repository
      uses: actions/checkout@v4

    - name: Configure python
      uses: actions/setup-python@v4
      with: 
        python-version: "3.11"
        cache: "pip3"
        cache-dependency-path: backend/requirements.txt
    
    - name: Install test utils
      run: pip3 install tox

    - name: Run linting
      run: tox -e lint


  lint-frontend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v4

    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: "npm"
      
    - name: Install test utils
      run: npm install ci

    - name: Run linting
      run: npm run lint 


  test:
    
  
  build-backend:


  build-frontend:
