name: master

on:
  push:
    branches: 
    - main

jobs:
  lint-backend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout backend repository
      uses: actions/checkout@v4

    - name: Configure python
      uses: actions/setup-python@v4
      with: 
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: backend/requirements.txt
    
    - name: Install Python linters
      run: pip install flake8 isort black
        
    - name: Run Python linters
      run: |
        echo "=== Running Flake8 ==="
        flake8 --config=backend/.flake8 backend/  
        echo "=== Running Black ==="
        black backend/ --check --diff
        echo "=== Running Isort ==="
        isort backend/ --check-only --diff
        echo " All Python linting checks passed!"


  lint-frontend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v4

    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        

    - name: Install test utils
      run: npm install eslint

    - name: Run linting
      run: cd frontend/ && npm run lint 
