name: master

on:
  push:
    branches:
    - main

env:
  REGISTRY: docker.io
  BACKEND_IMAGE_NAME: antoni0832/backend-app
  FRONTEND_IMAGE_NAME: antoni0832/frontend-app

jobs:
  lint-backend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout backend repository
      uses: actions/checkout@v4

    - name: Configure python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: backend/requirements.txt

    - name: Install Python linters
      run: pip install flake8 isort black

    - name: Run flake8
      run: flake8 --config=backend/.flake8 backend/ || true

    - name: Run black
      run: black backend/ --check --diff || true

    - name: Run isort
      run: isort backend/ --check-only --diff || true

  lint-frontend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v4

    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install test utils
      run: cd frontend/ && npm install eslint --save-dev && npm install

    - name: Run linting
      run: cd frontend/ && npm run lint || true

  build-backend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up docker hub account
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: backend/
        file: backend/Dockerfile
        push: true
        tags: ${{ env.BACKEND_IMAGE }}:latest
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up docker hub account
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: frontend/
        file: frontend/Dockerfile
        push: true
        tags: ${{ env.BACKEND_IMAGE }}:latest
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
