name: master

on:
  push:
    branches:
    - main

jobs:
  lint-backend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout backend repository
      uses: actions/checkout@v4

    - name: Configure python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: backend/requirements.txt

    - name: Install Python linters
      run: pip install flake8 isort black

    - name: Run flake8
      run: flake8 --config=backend/.flake8 backend/ || true

    - name: Run black
      run: black backend/ --check --diff || true

    - name: Run isort
      run: isort backend/ --check-only --diff || true

  lint-frontend:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v4

    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install and run ESLint
      run: |
        cd frontend/
        npm install eslint@9.0.0 --save-dev
        npm install
        npm run lint
